"""server default timestamps

Revision ID: 39ca197b9970
Revises: d3318b686dcc
Create Date: 2026-03-09 11:13:19.670110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ca197b9970'
down_revision: Union[str, Sequence[str], None] = 'd3318b686dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('statements', 'account_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('statements', 'opening_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('statements', 'closing_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('transactions', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('statements', 'closing_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('statements', 'opening_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('statements', 'account_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('accounts', 'uploaded_at')
    # ### end Alembic commands ###
